### ISSUE TITLE
direct url getting error resource not fond 

### ISSUE THREAD

**Issue by pamarthidrgarao** [amanganiello90/java-angular-web-app#1]
Ex
if hit the below url 
https://spring-boot-angular-app.herokuapp.com/user-profile

getting 

Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.
Thu Feb 01 11:34:25 UTC 2018
There was an unexpected error (type=Not Found, status=404).
No message available

**Comment by amanganiello90** [comment]
Hi @pamarthidrgarao,
If you click on dashboard for "user-profile", the issue is not exist.
![cattura](https://user-images.githubusercontent.com/20536757/35690043-30431e9e-0775-11e8-9566-d3b5089b8ff8.PNG)

However, my project is a tool to package whatever app, and in this repository there is an example app cloned from https://github.com/creativetimofficial/material-dashboard-angular project.

**This means that my project doesn't focus on the app creation but only on packaging process.**

So for this error, that is an application error (not for my packaging tool), you have to open an issue for that github repo.

Thanks.

**Comment by amanganiello90** [comment]
I have started new projects with angular and spring boot, and I find now that the routing issue is due to the embedded tomcat in spring boot jar. I will investigate to resolve it. Thanks

**Comment by amanganiello90** [comment]
@pamarthidrgarao , I have fixed the error with this: https://github.com/amanganiello90/java-angular-web-app/commit/5b23be879d5f1f03ff054236d36c6da202ecb9cc.

Thanks for the issue.
