### ISSUE TITLE
[Question] How to build frontend and backend directly on heroku?

### ISSUE THREAD

**Issue by pedroct92** [amanganiello90/java-angular-web-app#2]
Hi, nice work putting your project together It has helped me a lot. However, did you find a way to do both builds directly on heroku? from I have seen you do both builds locally and deploy the jar only. 

Thanks.

**Comment by amanganiello90** [comment]
Hi, you have to configure your github repo with heroku for continous integration:
https://devcenter.heroku.com/articles/github-integration#enabling-github-integration

**Comment by pedroct92** [comment]
Thanks a lot for the quick response. I've just found a nice [repository](https://github.com/spektrakel-blog/ng-in-the-enterprise) that does something closer to what I am looking for. In addition to that, I am gonna add the heroku buildpacks for both nodejs and java, it should work well. Thanks a lot!

**Comment by amanganiello90** [comment]
Maybe the best practise is to use a cloud continuous integration as travis (https://travis-ci.org/) because heroku doesn't build the custom project of this repo. After you can deploy on heroku with a script. I have just comitted a travis.yml (https://github.com/amanganiello90/java-angular-web-app/blob/master/.travis.yml) and script-deploy-heroku (https://github.com/amanganiello90/java-angular-web-app/blob/master/.travis-deploy-heroku.sh) example files.
Good luck

**Comment by amanganiello90** [comment]
Hi, I have resolved your question. You can read the guide on : https://github.com/amanganiello90/java-angular-web-app#automatic-build-and-deploy-with-travis .

Thanks a lot for your feedback. I'm very happy to give my devOps experience to improve open source projects. 
Have a nice day :)
